#ifndef GUARD_CONSTANTS_MAP_EVENT_IDS_H
#define GUARD_CONSTANTS_MAP_EVENT_IDS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/*/map.json
//

// MAP_BIRTH_ISLAND_EXTERIOR
#define LOCALID_BIRTH_ISLAND_EXTERIOR_ROCK 1
#define LOCALID_BIRTH_ISLAND_DEOXYS 2

// MAP_CELADON_CITY
#define LOCALID_CELADON_FAT_MAN 2
#define LOCALID_CELADON_POLIWRATH 3
#define LOCALID_CELADON_BORDER_TREE 10

// MAP_CELADON_CITY_CONDOMINIUMS_ROOF_ROOM
#define LOCALID_EEVEE_POKEBALL 2

// MAP_CELADON_CITY_GAME_CORNER
#define LOCALID_GAME_CORNER_GRUNT 11

// MAP_CELADON_CITY_POKEMON_CENTER_1F
#define LOCALID_CELADON_NURSE 1

// MAP_CERULEAN_CITY
#define LOCALID_CERULEAN_POLICEMAN 1
#define LOCALID_CERULEAN_GRUNT 2
#define LOCALID_CERULEAN_SLOWBRO 5
#define LOCALID_CERULEAN_LASS 6
#define LOCALID_CERULEAN_RIVAL 8
#define LOCALID_CERULEAN_WOMAN 11
#define LOCALID_CERULEAN_CAVE_GUARD 12

// MAP_CERULEAN_CITY_HOUSE4
#define LOCALID_WONDER_NEWS_BERRY_MAN 1

// MAP_CERULEAN_CITY_POKEMON_CENTER_1F
#define LOCALID_CERULEAN_NURSE 1

// MAP_CINNABAR_ISLAND
#define LOCALID_CINNABAR_BILL 3
#define LOCALID_CINNABAR_SEAGALLOP 4

// MAP_CINNABAR_ISLAND_GYM
#define LOCALID_QUINN 1
#define LOCALID_AVERY 3
#define LOCALID_RAMON 4
#define LOCALID_DEREK 5
#define LOCALID_DUSTY 6
#define LOCALID_ZAC 7

// MAP_CINNABAR_ISLAND_POKEMON_CENTER_1F
#define LOCALID_CINNABAR_NURSE 1
#define LOCALID_CINNABAR_POKEMON_CENTER_BILL 7

// MAP_FIVE_ISLAND_LOST_CAVE_ROOM10
#define LOCALID_LOST_CAVE_SELPHY 1

// MAP_FIVE_ISLAND_MEADOW
#define LOCALID_FIVE_ISLAND_MEADOW_BORDER_TREE 4

// MAP_FIVE_ISLAND_MEMORIAL_PILLAR
#define LOCALID_MEMORIAL_MAN 1

// MAP_FIVE_ISLAND_POKEMON_CENTER_1F
#define LOCALID_FIVE_ISLAND_NURSE 1

// MAP_FIVE_ISLAND_RESORT_GORGEOUS
#define LOCALID_RESORT_GORGEOUS_SELPHY 8

// MAP_FIVE_ISLAND_RESORT_GORGEOUS_HOUSE
#define LOCALID_RESORT_GORGEOUS_HOUSE_SELPHY 1
#define LOCALID_RESORT_GORGEOUS_HOUSE_BUTLER 2

// MAP_FIVE_ISLAND_ROCKET_WAREHOUSE
#define LOCALID_WAREHOUSE_GRUNT2 1
#define LOCALID_WAREHOUSE_GRUNT3 2
#define LOCALID_WAREHOUSE_ADMIN1 3
#define LOCALID_WAREHOUSE_ADMIN2 4

// MAP_FOUR_ISLAND
#define LOCALID_FOUR_ISLAND_DAYCARE_MAN 1
#define LOCALID_FOUR_ISLAND_RIVAL 10

// MAP_FOUR_ISLAND_HOUSE2
#define LOCALID_STICKER_MAN 1

// MAP_FOUR_ISLAND_ICEFALL_CAVE_BACK
#define LOCALID_ICEFALL_ROCKET1 1
#define LOCALID_ICEFALL_ROCKET2 2
#define LOCALID_ICEFALL_LORELEI 3
#define LOCALID_ICEFALL_ROCKET3 4

// MAP_FOUR_ISLAND_POKEMON_CENTER_1F
#define LOCALID_FOUR_ISLAND_NURSE 1

// MAP_FOUR_ISLAND_POKEMON_DAY_CARE
#define LOCALID_FOUR_ISLAND_DAYCARE_WOMAN 1

// MAP_FUCHSIA_CITY_POKEMON_CENTER_1F
#define LOCALID_FUCHSIA_NURSE 1

// MAP_INDIGO_PLATEAU_EXTERIOR
#define LOCALID_CREDITS_RIVAL 1
#define LOCALID_CREDITS_PROF_OAK 2

// MAP_INDIGO_PLATEAU_POKEMON_CENTER_1F
#define LOCALID_LEAGUE_NURSE 2
#define LOCALID_LEAGUE_DOOR_GUARD 4

// MAP_LAVENDER_TOWN_POKEMON_CENTER_1F
#define LOCALID_LAVENDER_NURSE 1

// MAP_MT_EMBER_EXTERIOR
#define LOCALID_MT_EMBER_GRUNT1 2
#define LOCALID_MT_EMBER_GRUNT2 3

// MAP_MT_EMBER_RUBY_PATH_B3F
#define LOCALID_RUBY 1

// MAP_MT_MOON_B2F
#define LOCALID_DOME_FOSSIL 1
#define LOCALID_HELIX_FOSSIL 2
#define LOCALID_MIGUEL 3

// MAP_NAVEL_ROCK_BASE
#define LOCALID_NAVEL_ROCK_LUGIA 1

// MAP_NAVEL_ROCK_SUMMIT
#define LOCALID_NAVEL_ROCK_HO_OH 1

// MAP_ONE_ISLAND
#define LOCALID_ONE_ISLAND_BILL 1

// MAP_ONE_ISLAND_POKEMON_CENTER_1F
#define LOCALID_ONE_ISLAND_NURSE 1
#define LOCALID_ONE_ISLAND_POKEMON_CENTER_BILL 2
#define LOCALID_CELIO 3

// MAP_PALLET_TOWN
#define LOCALID_PALLET_SIGN_LADY 1
#define LOCALID_PALLET_FAT_MAN 2
#define LOCALID_PALLET_PROF_OAK 3

// MAP_PALLET_TOWN_PLAYERS_HOUSE_1F
#define LOCALID_MOM 1

// MAP_PALLET_TOWN_PROFESSOR_OAKS_LAB
#define LOCALID_OAKS_LAB_PROF_OAK 4
#define LOCALID_BULBASAUR_BALL 5
#define LOCALID_SQUIRTLE_BALL 6
#define LOCALID_CHARMANDER_BALL 7
#define LOCALID_OAKS_LAB_RIVAL 8
#define LOCALID_POKEDEX_1 9
#define LOCALID_POKEDEX_2 10

// MAP_PALLET_TOWN_RIVALS_HOUSE
#define LOCALID_DAISY 1
#define LOCALID_TOWN_MAP 2

// MAP_PEWTER_CITY
#define LOCALID_PEWTER_MUSEUM_GUIDE 2
#define LOCALID_PEWTER_GYM_GUIDE 5
#define LOCALID_PEWTER_AIDE 7

// MAP_PEWTER_CITY_HOUSE1
#define LOCALID_PEWTER_HOUSE_NIDORAN 3

// MAP_PEWTER_CITY_MUSEUM_1F
#define LOCALID_MUSEUM_SCIENTIST1 1
#define LOCALID_OLD_AMBER 4

// MAP_PEWTER_CITY_POKEMON_CENTER_1F
#define LOCALID_PEWTER_NURSE 3

// MAP_POKEMON_LEAGUE_BRUNOS_ROOM
#define LOCALID_BRUNO 1

// MAP_POKEMON_LEAGUE_CHAMPIONS_ROOM
#define LOCALID_CHAMPIONS_ROOM_RIVAL 1
#define LOCALID_CHAMPIONS_ROOM_PROF_OAK 2

// MAP_POKEMON_LEAGUE_HALL_OF_FAME
#define LOCALID_HALL_OF_FAME_PROF_OAK 1

// MAP_POKEMON_LEAGUE_LANCES_ROOM
#define LOCALID_LANCE 1

// MAP_POKEMON_TOWER_2F
#define LOCALID_POKEMON_TOWER_RIVAL 1

// MAP_POKEMON_TOWER_7F
#define LOCALID_POKEMON_TOWER_GRUNT1 2
#define LOCALID_POKEMON_TOWER_GRUNT2 3
#define LOCALID_POKEMON_TOWER_GRUNT3 4

// MAP_ROCKET_HIDEOUT_B4F
#define LOCALID_HIDEOUT_GIOVANNI 1
#define LOCALID_SILPH_SCOPE 2
#define LOCALID_LIFT_KEY 4

// MAP_ROUTE10_POKEMON_CENTER_1F
#define LOCALID_ROUTE10_NURSE 1

// MAP_ROUTE14
#define LOCALID_ROUTE14_BORDER_TREE 13

// MAP_ROUTE16
#define LOCALID_ROUTE16_CUT_TREE 7

// MAP_ROUTE22
#define LOCALID_ROUTE22_RIVAL 1

// MAP_ROUTE23
#define LOCALID_CASCADE_BADGE_GUARD 1
#define LOCALID_THUNDER_BADGE_GUARD 2
#define LOCALID_RAINBOW_BADGE_GUARD 3
#define LOCALID_SOUL_BADGE_GUARD 4
#define LOCALID_MARSH_BADGE_GUARD 5
#define LOCALID_VOLCANO_BADGE_GUARD 6
#define LOCALID_EARTH_BADGE_GUARD 7

// MAP_ROUTE24
#define LOCALID_ROUTE24_ROCKET 1

// MAP_ROUTE25_SEA_COTTAGE
#define LOCALID_BILL_HUMAN 1
#define LOCALID_BILL_CLEFAIRY 2

// MAP_ROUTE4_POKEMON_CENTER_1F
#define LOCALID_ROUTE4_NURSE 1

// MAP_ROUTE9
#define LOCALID_ROUTE9_CUT_TREE 10

// MAP_SSANNE_2F_CORRIDOR
#define LOCALID_SS_ANNE_RIVAL 1

// MAP_SSANNE_CAPTAINS_OFFICE
#define LOCALID_SS_ANNE_CAPTAIN 1

// MAP_SSANNE_EXTERIOR
#define LOCALID_SS_ANNE 1

// MAP_SAFFRON_CITY
#define LOCALID_SAFFRON_DOOR_GUARD_GRUNT 6

// MAP_SAFFRON_CITY_DOJO
#define LOCALID_KARATE_MASTER 5

// MAP_SAFFRON_CITY_POKEMON_CENTER_1F
#define LOCALID_SAFFRON_NURSE 1

// MAP_SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB
#define LOCALID_TRAINER_FAN_CLUB_BATTLE_GIRL 1
#define LOCALID_TRAINER_FAN_CLUB_LITTLE_GIRL 2
#define LOCALID_TRAINER_FAN_CLUB_YOUNGSTER 3
#define LOCALID_TRAINER_FAN_CLUB_GENTLEMAN 4
#define LOCALID_TRAINER_FAN_CLUB_WOMAN 5
#define LOCALID_TRAINER_FAN_CLUB_ROCKER 6
#define LOCALID_TRAINER_FAN_CLUB_BEAUTY 7
#define LOCALID_TRAINER_FAN_CLUB_BLACK_BELT 8

// MAP_SEVEN_ISLAND
#define LOCALID_SWORDS_DANCE_TUTOR 1

// MAP_SEVEN_ISLAND_HOUSE_ROOM1
#define LOCALID_SEVEN_ISLAND_HOUSE_OLD_WOMAN 1

// MAP_SEVEN_ISLAND_POKEMON_CENTER_1F
#define LOCALID_SEVEN_ISLAND_NURSE 1

// MAP_SEVEN_ISLAND_SEVAULT_CANYON_HOUSE
#define LOCALID_CHANSEY_DANCE_MAN 1

// MAP_SEVEN_ISLAND_SEVAULT_CANYON_TANOBY_KEY
#define LOCALID_TANOBY_KEY_BOULDER1 1
#define LOCALID_TANOBY_KEY_BOULDER2 2
#define LOCALID_TANOBY_KEY_BOULDER3 3
#define LOCALID_TANOBY_KEY_BOULDER4 4
#define LOCALID_TANOBY_KEY_BOULDER5 5
#define LOCALID_TANOBY_KEY_BOULDER6 6
#define LOCALID_TANOBY_KEY_BOULDER7 7

// MAP_SILPH_CO_11F
#define LOCALID_SILPH_CO_GIOVANNI 3
#define LOCALID_SILPH_CO_11F_GRUNT1 4
#define LOCALID_SILPH_CO_11F_GRUNT2 6

// MAP_SILPH_CO_7F
#define LOCALID_SILPH_CO_RIVAL 1
#define LOCALID_SILPH_CO_7F_WORKER_M2 8

// MAP_SIX_ISLAND_DOTTED_HOLE_SAPPHIRE_ROOM
#define LOCALID_SAPPHIRE 1
#define LOCALID_DOTTED_HOLE_THIEF 2

// MAP_SIX_ISLAND_POKEMON_CENTER_1F
#define LOCALID_SIX_ISLAND_NURSE 1
#define LOCALID_SIX_ISLAND_RIVAL 2

// MAP_SIX_ISLAND_RUIN_VALLEY
#define LOCALID_RUIN_VALLEY_SCIENTIST 1

// MAP_THREE_ISLAND
#define LOCALID_THREE_ISLAND_ANTIBIKER1 1
#define LOCALID_THREE_ISLAND_ANTIBIKER2 2
#define LOCALID_PAXTON 3
#define LOCALID_THREE_ISLAND_BIKER3 4
#define LOCALID_THREE_ISLAND_BIKER1 5
#define LOCALID_THREE_ISLAND_BIKER4 6
#define LOCALID_THREE_ISLAND_BIKER2 7
#define LOCALID_THREE_ISLAND_BIKER5 8
#define LOCALID_THREE_ISLAND_BIKER6 14

// MAP_THREE_ISLAND_BERRY_FOREST
#define LOCALID_BERRY_FOREST_LOSTELLE 1

// MAP_THREE_ISLAND_DUNSPARCE_TUNNEL
#define LOCALID_PROSPECTOR 1

// MAP_THREE_ISLAND_POKEMON_CENTER_1F
#define LOCALID_THREE_ISLAND_NURSE 1

// MAP_TRAINER_TOWER_1F
#define LOCALID_TOWER_TRAINER_DOUBLES1 2
#define LOCALID_TOWER_TRAINER_SINGLES 3
#define LOCALID_TOWER_TRAINER_KNOCKOUT 4
#define LOCALID_TOWER_TRAINER_DOUBLES2 5

// MAP_TRAINER_TOWER_2F
#define LOCALID_TOWER_TRAINER_DOUBLES1 2
#define LOCALID_TOWER_TRAINER_SINGLES 3
#define LOCALID_TOWER_TRAINER_KNOCKOUT 4
#define LOCALID_TOWER_TRAINER_DOUBLES2 5

// MAP_TRAINER_TOWER_3F
#define LOCALID_TOWER_TRAINER_DOUBLES1 2
#define LOCALID_TOWER_TRAINER_SINGLES 3
#define LOCALID_TOWER_TRAINER_KNOCKOUT 4
#define LOCALID_TOWER_TRAINER_DOUBLES2 5

// MAP_TRAINER_TOWER_4F
#define LOCALID_TOWER_TRAINER_DOUBLES1 2
#define LOCALID_TOWER_TRAINER_SINGLES 3
#define LOCALID_TOWER_TRAINER_KNOCKOUT 4
#define LOCALID_TOWER_TRAINER_DOUBLES2 5

// MAP_TRAINER_TOWER_5F
#define LOCALID_TOWER_TRAINER_DOUBLES1 2
#define LOCALID_TOWER_TRAINER_SINGLES 3
#define LOCALID_TOWER_TRAINER_KNOCKOUT 4
#define LOCALID_TOWER_TRAINER_DOUBLES2 5

// MAP_TRAINER_TOWER_6F
#define LOCALID_TOWER_TRAINER_DOUBLES1 2
#define LOCALID_TOWER_TRAINER_SINGLES 3
#define LOCALID_TOWER_TRAINER_KNOCKOUT 4
#define LOCALID_TOWER_TRAINER_DOUBLES2 5

// MAP_TRAINER_TOWER_7F
#define LOCALID_TOWER_TRAINER_DOUBLES1 2
#define LOCALID_TOWER_TRAINER_SINGLES 3
#define LOCALID_TOWER_TRAINER_KNOCKOUT 4
#define LOCALID_TOWER_TRAINER_DOUBLES2 5

// MAP_TRAINER_TOWER_8F
#define LOCALID_TOWER_TRAINER_DOUBLES1 2
#define LOCALID_TOWER_TRAINER_SINGLES 3
#define LOCALID_TOWER_TRAINER_KNOCKOUT 4
#define LOCALID_TOWER_TRAINER_DOUBLES2 5

// MAP_TRAINER_TOWER_LOBBY
#define LOCALID_TOWER_NURSE 1
#define LOCALID_TOWER_MART_CLERK 2
#define LOCALID_TOWER_RECEPTIONIST 3
#define LOCALID_TOWER_COOLTRAINER_F 4
#define LOCALID_TOWER_BALDING_MAN 5

// MAP_TWO_ISLAND_CAPE_BRINK_HOUSE
#define LOCALID_CAPE_BRINK_TUTOR 1

// MAP_TWO_ISLAND_JOYFUL_GAME_CORNER
#define LOCALID_JOYFUL_GAME_CORNER_DADDY 1
#define LOCALID_JOYFUL_GAME_CORNER_BIKER 2
#define LOCALID_JOYFUL_GAME_CORNER_LOSTELLE 3

// MAP_TWO_ISLAND_POKEMON_CENTER_1F
#define LOCALID_TWO_ISLAND_NURSE 1

// MAP_UNION_ROOM
#define LOCALID_UNION_ROOM_PLAYER_4 2
#define LOCALID_UNION_ROOM_PLAYER_8 3
#define LOCALID_UNION_ROOM_PLAYER_7 4
#define LOCALID_UNION_ROOM_PLAYER_6 5
#define LOCALID_UNION_ROOM_PLAYER_5 6
#define LOCALID_UNION_ROOM_PLAYER_3 7
#define LOCALID_UNION_ROOM_PLAYER_2 8
#define LOCALID_UNION_ROOM_PLAYER_1 9

// MAP_VERMILION_CITY
#define LOCALID_VERMILION_FERRY_SAILOR 6

// MAP_VERMILION_CITY_POKEMON_CENTER_1F
#define LOCALID_VERMILION_NURSE 1

// MAP_VERMILION_CITY_POKEMON_FAN_CLUB
#define LOCALID_POKEMON_FAN_CLUB_WOMAN 5
#define LOCALID_POKEMON_FAN_CLUB_FAT_MAN 6

// MAP_VICTORY_ROAD_1F
#define LOCALID_VICTORY_ROAD_1F_BOULDER 5

// MAP_VICTORY_ROAD_2F
#define LOCALID_VICTORY_ROAD_2F_BOULDER1 11
#define LOCALID_VICTORY_ROAD_2F_BOULDER2 12

// MAP_VICTORY_ROAD_3F
#define LOCALID_VICTORY_ROAD_3F_BOULDER1 7
#define LOCALID_VICTORY_ROAD_3F_BOULDER2 10

// MAP_VIRIDIAN_CITY
#define LOCALID_VIRIDIAN_OLD_MAN 3
#define LOCALID_TUTORIAL_MAN 4
#define LOCALID_VIRIDIAN_WOMAN 5
#define LOCALID_VIRIDIAN_BORDER_TREE 8

// MAP_VIRIDIAN_CITY_GYM
#define LOCALID_VIRIDIAN_GIOVANNI 8

// MAP_VIRIDIAN_CITY_MART
#define LOCALID_VIRIDIAN_MART_CLERK 1

// MAP_VIRIDIAN_CITY_POKEMON_CENTER_1F
#define LOCALID_VIRIDIAN_NURSE 1

// MAP_VIRIDIAN_CITY_SCHOOL
#define LOCALID_SCHOOL_WOMAN 1
#define LOCALID_SCHOOL_LASS 2

#endif // GUARD_CONSTANTS_MAP_EVENT_IDS_H
